/**
 * Automation Review Queue
 *
 * Users review pending commit groups and announcement objects
 * generated by the GitHub automation pipeline.
 */

import { auth } from "@clerk/nextjs/server";
import { supabaseAdmin } from "@/lib/supabase";
import Link from "next/link";
import { AutomationClient } from "@/components/automation/automation-client";

export default async function AutomationPage() {
  const { userId } = await auth();
  if (!userId) return null;

  // Fetch pending commit groups (not yet turned into announcements)
  const { data: pendingGroups } = await supabaseAdmin
    .from("commit_groups")
    .select("*")
    .eq("clerk_user_id", userId)
    .in("status", ["pending", "processing"])
    .order("created_at", { ascending: false })
    .limit(30);

  // Fetch draft announcements (generated, awaiting user review)
  const { data: draftAnnouncements } = await supabaseAdmin
    .from("announcement_objects")
    .select(`
      *,
      content_scores (format, score, hook_strength, clarity, benefit_emphasis, novelty, feedback, needs_regeneration)
    `)
    .eq("clerk_user_id", userId)
    .eq("status", "draft")
    .order("created_at", { ascending: false })
    .limit(20);

  // Stats
  const [
    { count: totalAnnounced },
    { count: totalPending },
  ] = await Promise.all([
    supabaseAdmin
      .from("announcement_objects")
      .select("*", { count: "exact", head: true })
      .eq("clerk_user_id", userId)
      .eq("status", "published"),
    supabaseAdmin
      .from("commit_groups")
      .select("*", { count: "exact", head: true })
      .eq("clerk_user_id", userId)
      .eq("status", "pending"),
  ]);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">Automation</h1>
          <p className="text-zinc-500 text-sm mt-1">
            GitHub commits converted to marketing content — review before publishing.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div className="text-center">
            <p className="text-xl font-bold tabular-nums">{totalPending ?? 0}</p>
            <p className="text-[10px] text-zinc-600 uppercase tracking-widest">Pending</p>
          </div>
          <div className="text-center">
            <p className="text-xl font-bold tabular-nums">{totalAnnounced ?? 0}</p>
            <p className="text-[10px] text-zinc-600 uppercase tracking-widest">Announced</p>
          </div>
        </div>
      </div>

      {/* Pipeline diagram */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-4">
        <p className="text-[10px] text-zinc-600 uppercase tracking-widest mb-3">How it works</p>
        <div className="flex items-center gap-2 text-xs text-zinc-500 flex-wrap">
          {[
            "GitHub push",
            "Commit grouping",
            "Feature detection",
            "Benefit extraction",
            "Announcement draft",
            "Your review",
            "Published content",
          ].map((step, i, arr) => (
            <span key={step} className="flex items-center gap-2">
              <span className={i === 5 ? "text-white font-medium" : ""}>{step}</span>
              {i < arr.length - 1 && <span className="text-zinc-700">→</span>}
            </span>
          ))}
        </div>
      </div>

      {(pendingGroups ?? []).length === 0 && (draftAnnouncements ?? []).length === 0 ? (
        <div className="text-center py-16 border border-zinc-800/50 rounded-xl">
          <p className="text-zinc-500 text-sm">No pending automation items.</p>
          <p className="text-zinc-700 text-xs mt-2">
            Connect a GitHub repo and push commits to see them here.
          </p>
          <Link
            href="/github"
            className="inline-block mt-4 text-xs px-4 py-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-white transition-colors"
          >
            Connect GitHub →
          </Link>
        </div>
      ) : (
        <AutomationClient
          initialGroups={pendingGroups ?? []}
          initialAnnouncements={(draftAnnouncements ?? []) as Record<string, unknown>[]}
        />
      )}
    </div>
  );
}
